Repository ShoanRohan/Psagot, pull requests merged in 2025-07, with the labels that each got.

#181 DDcomplate component new course
  psagot-client/src/components/NewCourse.jsx
Labels: teamJ1

#187 שינויים
  psagot-client/src/components/AddAndUpdateUserPopUp.jsx
  psagot-client/src/components/EditProfile.jsx
  psagot-client/src/components/SideBar.jsx
  psagot-client/src/routers/AppRouter.js
  psagot-client/src/styles/AddAndUpdateUserPopUp.css
  psagot-client/src/styles/EditProfile.css
Labels: teamH2

#191 meetingSchedule
  DL/RoomDL.cs
  psagot-client/src/components/MeetingSchedule.jsx
  psagot-client/src/components/RoomsScheduleGrid.jsx
  psagot-client/src/components/RoomsScheduleSearch.jsx
  psagot-client/src/features/store.js
  psagot-client/src/pages/RoomsPage.jsx
  psagot-client/src/routers/AppRouter.js
Labels: teamJ3

#192 GetMeetingBy Date
  BL/BL.csproj
  Psagot/appsettings.json
  psagot-client/src/components/RoomsScheduleGrid.jsx
  psagot-client/src/features/meeting/meetingActions.js
  psagot-client/src/features/meeting/meetingSlice.js
  psagot-client/src/pages/RoomsPage.jsx
  psagot-client/src/utils/meetingUtil.js
Labels: teamJ3
