Repository ShoanRohan/Psagot, pull requests merged in 2025-04, with the labels that each got.

#94 Tami kostiner j1
  BL/UserBL.cs
  DL/UserDL.cs
  Entities/MappingProfile.cs
  Psagot/Controllers/UserController.cs
  psagot-client/package-lock.json
  psagot-client/package.json
  psagot-client/src/assets/icons/circle-plus.png
  psagot-client/src/assets/icons/edit.png
  psagot-client/src/assets/icons/image 6.png
  psagot-client/src/components/UserGrid.jsx
  psagot-client/src/css/UserTableDesign.css
  psagot-client/src/features/user/userAction.js
  psagot-client/src/features/user/userSlice.js
  psagot-client/src/index.js
  psagot-client/src/pages/Layout.jsx
  psagot-client/src/pages/UserManagement.jsx
  psagot-client/src/routers/AppRouter.js
  psagot-client/src/utils/api.js
  psagot-client/src/utils/userUtil.js
Labels: teamJ1

#140 פונקצית GetAllRoomsBySearchWithPagination סרבר וקליינט
  BL/IRoomBL.cs
  BL/RoomBL.cs
  DL/IRoomDL.cs
  DL/RoomDL.cs
  Psagot/Controllers/RoomController.cs
  psagot-client/src/features/room/roomSlice.js
  psagot-client/src/utils/roomUtil.js
Labels: teamJ3

#115 GetCoordinatorsAndLecturers
  BL/IUserBL.cs
  BL/UserBL.cs
  DL/IDayDL.cs
  DL/IUserDL.cs
  DL/UserDL.cs
  Psagot/Controllers/UserController.cs
  Psagot/Controllers/UserTypeController.cs
  script DB/createAllTables.sql
Labels: teamH2
