Repository ShoanRohan/Psagot, pull requests merged in 2025-01, with the labels that each got.

#45 func UpdateTopic&DeleteTopic
  BL/ITopicBL.cs
  BL/TopicBL.cs
  DL/ITopicDL.cs
  DL/TopicDL.cs
  Psagot/Controllers/TopicController.cs
Labels: teamJ3

#61 GetById
  BL/IScheduleForTopicBL.cs
  BL/ITopicBL.cs
  BL/IUserTypeBL.cs
  BL/ScheduleForTopicBL.cs
  BL/TopicBL.cs
  DL/IScheduleForTopicDL.cs
  DL/ITopicDL.cs
  DL/ScheduleForTopicDL.cs
  DL/TopicDL.cs
  Psagot/Controllers/ScheduleForTopicController.cs
  Psagot/Controllers/TopicController.cs
Labels: teamJ3

#33 Ofrat h3 add func GetAllScheduleForTopic
  .gitignore
  BL/IScheduleForTopicBL.cs
  BL/ScheduleForTopicBL.cs
  DL/IScheduleForTopicDL.cs
  DL/ScheduleForTopicDL.cs
  Psagot/Controllers/ScheduleForTopicController.cs
  Psagot/Controllers/UserTypeController.cs
  Psagot/appsettings.json
Labels: teamH3

#21 add function GetAllScheduleForTopicByTopicId
  BL/IScheduleForTopicBL.cs
  BL/ScheduleForTopicBL.cs
  DL/IScheduleForTopicDL.cs
  DL/ScheduleForTopicDL.cs
  Psagot/Controllers/ScheduleForTopicController.cs
  Psagot/appsettings.json
  psagot-client/src/utils/api.js
Labels: teamH3

#35 GetScheduleForTopicById
  BL/IScheduleForTopicBL.cs
  BL/ScheduleForTopicBL.cs
  DL/IScheduleForTopicDL.cs
  DL/ScheduleForTopicDL.cs
  Psagot/Controllers/ScheduleForTopicController.cs
  Psagot/appsettings.json
  psagot-client/package-lock.json
  psagot-client/package.json
Labels: teamH3

#73 change deleteTopic
  Psagot/Controllers/TopicController.cs
Labels: teamJ3

#74 add topic-util and topic-feature with all the functions
  psagot-client/src/features/store.js
  psagot-client/src/features/topic/topicActions.js
  psagot-client/src/features/topic/topicSlice.js
  psagot-client/src/utils/topicUtil.js
Labels: teamJ3

#34 יצירת פונקציה UpdateScheduleForTopic
  BL/IScheduleForTopicBL.cs
  DL/IScheduleForTopicDL.cs
  Psagot/Controllers/ScheduleForTopicController.cs
  Psagot/appsettings.json
Labels: teamH3

#75 add ScheduleForTopic client - utils, actions & slice
  BL/IScheduleForTopicBL.cs
  DL/IScheduleForTopicDL.cs
  Psagot/appsettings.json
  psagot-client/src/features/scheduleForTopic/scheduleForTopicActions.js
  psagot-client/src/features/scheduleForTopic/scheduleForTopicSlice.js
  psagot-client/src/features/store.js
  psagot-client/src/utils/scheduleForTopicUtil.js
Labels: teamH3

#65 Haifa 2 - Task 2 - Added GetAllMeetings implements in MeetingUtil , MeetingSlice & MeetingActions
  psagot-client/src/features/meeting/meetingActions.js
  psagot-client/src/features/meeting/meetingSlice.js
  psagot-client/src/utils/meetingUtil.js
Labels: teamH2

#78 Haifa 2 - Task 2: updateMeeting implementation in Util & Actions & Slice.
  psagot-client/src/features/meeting/meetingActions.js
  psagot-client/src/features/meeting/meetingSlice.js
  psagot-client/src/utils/meetingUtil.js
Labels: teamH2

#69 Haifa 1 - Task 2 - Add addDaysForCourse implements in Utile, Slice & Actions
  BL/DaysForCourseBL.cs
  BL/IDaysForCourseBL.cs
  DL/DaysForCourseDL.cs
  DL/IDaysForCourseDL.cs
  Psagot/Controllers/DaysForCourseController.cs
  psagot-client/src/features/daysForCourse/daysForCourseActions.js
  psagot-client/src/features/daysForCourse/daysForCourseSlice.js
  psagot-client/src/utils/daysForCourseUtil.js
Labels: teamH1

#68 Haifa 1 - Task 2 - Add daysForCourseByCourseId implements in Util & Slice & Actions.
  psagot-client/src/features/daysForCourse/daysForCourseActions.js
  psagot-client/src/features/daysForCourse/daysForCourseSlice.js
  psagot-client/src/utils/daysForCourseUtil.js
Labels: teamH1

#70 Haifa 1 - Task2 add function getalldaysforcourse client
  psagot-client/src/features/daysForCourse/daysForCourseActions.js
  psagot-client/src/features/daysForCourse/daysForCourseSlice.js
  psagot-client/src/utils/daysForCourseUtil.js
Labels: teamH1

#79 Haifa 2- Task2- react function addMeeting in the meetingUtil, meetingActions, meetingSlice
  psagot-client/src/features/meeting/meetingActions.js
  psagot-client/src/features/meeting/meetingSlice.js
  psagot-client/src/utils/meetingUtil.js
Labels: teamH2

#77 update the func fetchAllTopicFotCourseByCourseId
  BL/ITopicBL.cs
  BL/TopicBL.cs
  DL/ITopicDL.cs
  DL/TopicDL.cs
  Psagot/Controllers/TopicController.cs
  psagot-client/src/features/topic/topicActions.js
  psagot-client/src/utils/topicUtil.js
Labels: teamJ3

#81 Yafit shama j1 UpdateCourse
  BL/CourseBL.cs
  BL/ICourseBL.cs
  DL/CourseDL.cs
  DL/ICourseDL.cs
  Entities/DTO/CourseDTO.cs
  Psagot/Controllers/CourseController.cs
Labels: teamJ1

#66 Haifa 2 -Task 2 - Add UpdateMeeting implements in Util, Slice & Actions.
  psagot-client/src/features/meeting/meetingActions.js
  psagot-client/src/features/meeting/meetingSlice.js
  psagot-client/src/utils/meetingUtil.js
Labels: teamH2

#67 Haifa1- Task 2 - Add getDaysForCourseById implements in Util, Slice & Actions.
  psagot-client/src/features/daysForCourse/daysForCourseActions.js
  psagot-client/src/features/daysForCourse/daysForCourseSlice.js
  psagot-client/src/utils/daysForCourseUtil.js
Labels: teamH1

#85 Task 3: Add UpdateDaysForCourse function implement in Utils , Slice &…
  psagot-client/src/features/daysForCourse/daysForCourseActions.js
  psagot-client/src/features/daysForCourse/daysForCourseSlice.js
  psagot-client/src/utils/daysForCourseUtil.js
Labels: teamH1

#82 Task2Haifa1:UpdateDaysForCourse -backend
  BL/DaysForCourseBL.cs
  BL/IDaysForCourseBL.cs
  DL/DaysForCourseDL.cs
  DL/IDaysForCourseDL.cs
  Psagot/Controllers/DaysForCourseController.cs
  Psagot/appsettings.json
Labels: teamH1

#97 login Changes
  BL/BL.csproj
  BL/IUserBL.cs
  BL/UserBL.cs
  DL/IUserDL.cs
  DL/UserDL.cs
  Entities/DTO/LoginDTO.cs
  Psagot/Controllers/UserController.cs
Labels: teamJ1

#98 course util, action and slice
  psagot-client/src/features/course/courseActions.js
  psagot-client/src/features/course/courseSlice.js
  psagot-client/src/features/store.js
  psagot-client/src/utils/courseUtil.js
Labels: teamJ1
