Repository ShoanRohan/Psagot, pull requests merged in 2025-05, with the labels that each got.

#135 prop up update & add users
  Psagot/appsettings.json
  psagot-client/package-lock.json
  psagot-client/package.json
  psagot-client/src/components/AddUserPopUp.jsx
  psagot-client/src/components/UserForm.jsx
  psagot-client/src/styles/AddUserPopUp.css
  psagot-client/src/styles/addUserModel.js
  psagot-client/src/styles/userModel.css
Labels: teamH2

#147 Tamar esty and bracha exel29.4.25
  Psagot/appsettings.json
  psagot-client/package-lock.json
  psagot-client/package.json
  psagot-client/src/assets/icons/xls-icon.png
  psagot-client/src/components/ExportToExcel.jsx
  psagot-client/src/styles/ExportToExcel.css
Labels: teamH2

#150 Haifa 1 - Task 6 - implemantation GetMeetingsByRange & GetMeetingsByPage functions
  BL/IMeetingBL.cs
  BL/ITopicBL.cs
  BL/MeetingBL.cs
  DL/IMeetingDL.cs
  DL/MeetingDL.cs
  Entities/DTO/EventDTO.cs
  Entities/MappingProfile.cs
  Psagot/Controllers/MeetingController.cs
  Psagot/appsettings.json
  psagot-client/package-lock.json
  psagot-client/package.json
  psagot-client/src/assets/icons/pen-to-square.svg
  psagot-client/src/assets/icons/trash.svg
  psagot-client/src/components/MeetingsTable.jsx
  psagot-client/src/features/meeting/meetingActions.js
  psagot-client/src/features/meeting/meetingSlice.js
  psagot-client/src/pages/Layout.jsx
  psagot-client/src/routers/AppRouter.js
  psagot-client/src/styles/MeetingsTableStyle.js
  psagot-client/src/styles/meetingsTable.css
  psagot-client/src/utils/meetingUtil.js
Labels: teamH1

#114 J3 tehila
  psagot-client/package-lock.json
  psagot-client/src/App.js
  psagot-client/src/components/RoomsScheduleSearch.jsx
  psagot-client/src/features/room/roomSlice.js
  psagot-client/src/routers/AppRouter.js
Labels: teamJ3

#145 Pas Itur
  BL/CourseBL.cs
  BL/ICourseBL.cs
  BL/IRoomBL.cs
  BL/RoomBL.cs
  BL/UserBL.cs
  DL/CourseDL.cs
  DL/ICourseDL.cs
  DL/IRoomDL.cs
  DL/MyDbContext.cs
  DL/RoomDL.cs
  DL/UserDL.cs
  Entities/DTO/CoursesDTO.cs
  Entities/DTO/RoomScheduleDTO.cs
  Entities/Entities.csproj
  Entities/MappingProfile.cs
  Entities/Models/Course.cs
  Entities/Models/Day.cs
  Entities/Models/DaysForCourse.cs
  Entities/Models/UserType.cs
  Psagot/Controllers/CourseController.cs
  Psagot/Controllers/RoomController.cs
  Psagot/Controllers/UserController.cs
  Psagot/Controllers/UserTypeController.cs
  Psagot/Program.cs
  Psagot/Properties/launchSettings.json
  psagot-client/package-lock.json
  psagot-client/package.json
  psagot-client/src/App.js
  psagot-client/src/assets/icons/borderAll.svg
  psagot-client/src/assets/icons/calendar.svg
  psagot-client/src/assets/icons/circle-plus.png
  psagot-client/src/assets/icons/courses.svg
  psagot-client/src/assets/icons/edit.png
  psagot-client/src/assets/icons/eye_icon.svg
  psagot-client/src/assets/icons/house.svg
  psagot-client/src/assets/icons/image 6.png
  psagot-client/src/assets/icons/networkWired.svg
  psagot-client/src/assets/icons/userIcon.svg
  psagot-client/src/assets/imgs/login_image.svg
  psagot-client/src/assets/imgs/logoWhite.svg
  psagot-client/src/assets/imgs/logo_psagot.svg
  psagot-client/src/components/Login.jsx
  psagot-client/src/components/RoomsScheduleGrid.jsx
  psagot-client/src/components/RoomsScheduleSearch.jsx
  psagot-client/src/components/Sidebar.jsx
  psagot-client/src/components/UserGrid.jsx
  psagot-client/src/css/UserTableDesign.css
  psagot-client/src/features/room/roomActions.js
  psagot-client/src/features/room/roomSlice.js
  psagot-client/src/features/user/userAction.js
  psagot-client/src/features/user/userSlice.js
  psagot-client/src/index.js
  psagot-client/src/pages/Layout.jsx
  psagot-client/src/pages/LoginPage.jsx
  psagot-client/src/pages/RoomsPage.jsx
  psagot-client/src/pages/UserManagement.jsx
  psagot-client/src/routers/AppRouter.js
  psagot-client/src/utils/api.js
  psagot-client/src/utils/roomUtil.js
  psagot-client/src/utils/userUtil.js
Labels: teamJ3

#153 update rooms & events from DB +style
  DL/RoomDL.cs
  Entities/DTO/RoomScheduleDTO.cs
  Psagot/Controllers/TopicController.cs
  psagot-client/package-lock.json
  psagot-client/package.json
  psagot-client/src/App.js
  psagot-client/src/components/Login.jsx
  psagot-client/src/components/RoomsScheduleGrid.jsx
  psagot-client/src/components/RoomsScheduleSearch.jsx
  psagot-client/src/features/daysForCourse/daysForCourseActions.js
  psagot-client/src/features/daysForCourse/daysForCourseSlice.js
  psagot-client/src/features/meeting/meetingSlice.js
  psagot-client/src/features/room/roomSlice.js
  psagot-client/src/features/topic/topicSlice.js
  psagot-client/src/pages/HomePage.jsx
  psagot-client/src/pages/LoginPage.jsx
  psagot-client/src/routers/AppRouter.js
  psagot-client/src/utils/roomUtil.js
Labels: teamJ3

#154 up
  psagot-client/package-lock.json
  psagot-client/src/components/Login.jsx
  psagot-client/src/components/RoomsScheduleGrid.jsx
  psagot-client/src/components/RoomsScheduleSearch.jsx
  psagot-client/src/pages/Layout.jsx
  psagot-client/src/routers/AppRouter.js
Labels: teamJ3

#110 generic popup with options.
  psagot-client/src/components/GenericPopup.jsx
  psagot-client/src/pages/HomePage.jsx
  psagot-client/src/style/GenericPopupStyle.jsx
Labels: teamH2

#156 HAIFA 1-view table rooms of day Hedva bracha t6 h1
  DL/MeetingDL.cs
  Entities/MappingProfile.cs
  Psagot/appsettings.json
  psagot-client/src/components/MeetingsTable.jsx
  psagot-client/src/components/RoomTable.jsx
  psagot-client/src/features/meeting/meetingActions.js
  psagot-client/src/features/meeting/meetingSlice.js
  psagot-client/src/routers/AppRouter.js
  psagot-client/src/styles/MeetingsTableStyle.js
  psagot-client/src/styles/RoomTable.css
  psagot-client/src/utils/meetingUtil.js
Labels: teamH1

#130 create and style calendar
  Entities/MappingProfile.cs
  Psagot/appsettings.json
  psagot-client/package-lock.json
  psagot-client/package.json
  psagot-client/src/App.css
  psagot-client/src/assets/imgs/pdf.png
  psagot-client/src/components/Calendar.jsx
  psagot-client/src/components/CalendarHeader.jsx
  psagot-client/src/components/CalendarHeaderStyle.jsx
  psagot-client/src/components/CalendarStyle.jsx
  psagot-client/src/components/DayView.jsx
  psagot-client/src/components/MonthView.jsx
  psagot-client/src/components/NavigationBar.jsx
  psagot-client/src/components/RoomsHeader.jsx
  psagot-client/src/components/RoomsHeaderStyle.jsx
  psagot-client/src/components/Section.jsx
  psagot-client/src/components/SideBar.jsx
  psagot-client/src/components/WeekView.jsx
  psagot-client/src/features/topic/topicSlice.js
  psagot-client/src/pages/CalendarPage.jsx
  psagot-client/src/pages/Layout.jsx
  psagot-client/src/routers/AppRouter.js
  psagot-client/src/styles/SideBar.css
Labels: teamH1
