Repository ShoanRohan/Psagot, pull requests merged in 2025-03, with the labels that each got.

#126 Michal 3 login page j1
  psagot-client/package-lock.json
  psagot-client/package.json
  psagot-client/public/index.html
  psagot-client/src/assets/icons/eye_icon.svg
  psagot-client/src/assets/imgs/login_image.svg
  psagot-client/src/assets/imgs/logo_psagot.svg
  psagot-client/src/components/Header.jsx
  psagot-client/src/components/Login.jsx
  psagot-client/src/pages/Layout.jsx
  psagot-client/src/pages/LoginPage.jsx
  psagot-client/src/routers/AppRouter.js
Labels: teamJ1

#132 add GetAllRoomsBySearchWithPagination to client
  psagot-client/src/features/room/roomActions.js
  psagot-client/src/features/room/roomSlice.js
  psagot-client/src/utils/roomUtil.js
Labels: teamJ3

#133 update roomUtil
  psagot-client/src/utils/roomUtil.js
Labels: teamJ3

#136 Yafit shama j1
  psagot-client/src/assets/icons/borderAll.svg
  psagot-client/src/assets/icons/calendar.svg
  psagot-client/src/assets/icons/courses.svg
  psagot-client/src/assets/icons/house.svg
  psagot-client/src/assets/icons/networkWired.svg
  psagot-client/src/assets/icons/userIcon.svg
  psagot-client/src/assets/imgs/logoWhite.svg
  psagot-client/src/components/Sidebar.jsx
  psagot-client/src/index.css
  psagot-client/src/pages/Layout.jsx
  psagot-client/src/routers/AppRouter.js
Labels: enhancement

#138 Haifa 1 - Task adding SideBar Commponent and style - Dd ron bracha h1 task5
  psagot-client/package-lock.json
  psagot-client/public/assets/logo_psagot.png
  psagot-client/public/favicon.ico
  psagot-client/src/components/Header.jsx
  psagot-client/src/components/SideBar.jsx
  psagot-client/src/pages/Layout.jsx
  psagot-client/src/routers/AppRouter.js
  psagot-client/src/styles/SideBar.css
Labels: teamH1
